In [5]:
import os, sys, inspect
import numpy as np
import matplotlib.pyplot as plt
# add parent dir to system dir
currdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
rootdir = os.path.dirname(currdir)
sys.path.insert(0, rootdir)

from src.plot import bar
import pandas as pd

In [8]:
# Importing file
data = "../data/int/realestate_demographics.csv"
# Reading the file
df_data = pd.read_csv(data)
df_data

,Zip Code,Year,Month,Home Value Index,Median Listing Price,Median Listing Price Per sqf,Sales,Median Income (dollars),Number of Households,School Rating (Parent),...,Liquor Store Count,Wal-Mart Count,Starbucks Count,Target Count,Inventory Measure,Median Price Cut,Median Price of Reduction,Median Rental Price,Latitude,Longitude
0,78701,1996,4,152500.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
1,78701,1996,5,153600.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
2,78701,1996,6,154600.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
3,78701,1996,7,155500.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
4,78701,1996,8,156300.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
5,78701,1996,9,157300.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
6,78701,1996,10,158300.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
7,78701,1996,11,159300.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
8,78701,1996,12,160400.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
9,78701,1997,1,161900.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
10,78701,1997,2,163500.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
11,78701,1997,3,164800.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
12,78701,1997,4,166300.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
13,78701,1997,5,167700.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
14,78701,1997,6,169000.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
15,78701,1997,7,170200.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
16,78701,1997,8,171500.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
17,78701,1997,9,172900.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
18,78701,1997,10,174500.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
19,78701,1997,11,176100.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
20,78701,1997,12,178000.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
21,78701,1998,1,180200.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
22,78701,1998,2,182700.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
23,78701,1998,3,185000.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
24,78701,1998,4,187500.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
25,78701,1998,5,189800.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
26,78701,1998,6,191800.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
27,78701,1998,7,193700.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
28,78701,1998,8,195500.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
29,78701,1998,9,197300.0,NaN,NaN,NaN,NaN,NaN,2.8,...,61,1,29,7,NaN,NaN,NaN,NaN,30.272921,-97.744386
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10835,78759,2015,11,381700.0,441250.0,205.696597,20.0,71517.666667,19848.0,3.0,...,22,1,11,4,NaN,8700.0,2.222222,1150.0,30.401356,-97.752535
10836,78759,2015,12,383600.0,499000.0,207.827217,36.0,71647.000000,19851.0,3.0,...,22,1,11,4,NaN,9300.0,1.896924,1092.5,30.401356,-97.752535
10837,78759,2016,1,385400.0,442250.0,203.488372,23.0,71874.666667,19873.0,3.0,...,22,1,11,4,NaN,12005.0,2.767733,1150.0,30.401356,-97.752535
10838,78759,2016,2,387400.0,425000.0,205.217125,17.0,72102.333333,19895.0,3.0,...,22,1,11,4,NaN,10950.0,2.439903,1183.0,30.401356,-97.752535
10839,78759,2016,3,390200.0,449900.0,207.720382,39.0,72330.000000,19917.0,3.0,...,22,1,11,4,NaN,8550.0,2.029293,1150.0,30.401356,-97.752535
10840,78759,2016,4,393900.0,459000.0,208.333333,42.0,72557.666667,19940.0,3.0,...,22,1,11,4,NaN,10000.0,2.247191,1020.0,30.401356,-97.752535
10841,78759,2016,5,398200.0,459900.0,210.560810,38.0,72785.333333,19962.0,3.0,...,22,1,11,4,NaN,15000.0,2.438489,1017.5,30.401356,-97.752535
10842,78759,2016,6,402100.0,499900.0,220.036878,2.0,73013.000000,19984.0,3.0,...,22,1,11,4,NaN,10000.0,2.298851,1064.5,30.401356,-97.752535
10843,78759,2016,7,405300.0,469000.0,221.714921,NaN,73240.666667,20006.0,3.0,...,22,1,11,4,NaN,10000.0,2.280913,1134.0,30.401356,-97.752535
10844,78759,2016,8,408600.0,465000.0,221.164603,NaN,73468.333333,20029.0,3.0,...,22,1,11,4,NaN,14000.0,2.614379,1118.0,30.401356,-97.752535
10845,78759,2016,9,411200.0,449900.0,211.320755,NaN,73696.000000,20051.0,3.0,...,22,1,11,4,NaN,10000.0,2.347220,1064.5,30.401356,-97.752535
10846,78759,2016,10,413200.0,449000.0,213.825163,NaN,73923.666667,20073.0,3.0,...,22,1,11,4,NaN,10000.0,2.500000,1085.0,30.401356,-97.752535
10847,78759,2016,11,414500.0,454950.0,213.365155,NaN,74151.333333,20095.0,3.0,...,22,1,11,4,NaN,8000.0,1.876507,1050.0,30.401356,-97.752535
10848,78759,2016,12,414700.0,440000.0,214.209147,NaN,74379.000000,20118.0,3.0,...,22,1,11,4,NaN,9400.0,2.812960,1050.0,30.401356,-97.752535
10849,78759,2017,1,415200.0,449000.0,211.440158,NaN,NaN,NaN,3.0,...,22,1,11,4,NaN,9000.0,1.960807,1166.5,30.401356,-97.752535
10850,78759,2017,2,416600.0,469900.0,219.317489,NaN,NaN,NaN,3.0,...,22,1,11,4,NaN,10000.0,2.670319,1230.0,30.401356,-97.752535
10851,78759,2017,3,417900.0,499900.0,221.305326,NaN,NaN,NaN,3.0,...,22,1,11,4,NaN,10900.0,3.081664,1307.0,30.401356,-97.752535
10852,78759,2017,4,418900.0,499900.0,220.808913,NaN,NaN,NaN,3.0,...,22,1,11,4,NaN,16000.0,3.032142,1344.0,30.401356,-97.752535
10853,78759,2017,5,419400.0,469850.0,221.014921,NaN,NaN,NaN,3.0,...,22,1,11,4,NaN,14500.0,2.315822,1400.0,30.401356,-97.752535
10854,78759,2017,6,419100.0,443950.0,217.727263,NaN,NaN,NaN,3.0,...,22,1,11,4,NaN,10100.0,2.759770,1515.0,30.401356,-97.752535
10855,78759,2017,7,418200.0,425000.0,219.235589,NaN,NaN,NaN,3.0,...,22,1,11,4,NaN,10700.0,2.673846,1500.0,30.401356,-97.752535
10856,78759,2017,8,418100.0,425000.0,222.783944,NaN,NaN,NaN,3.0,...,22,1,11,4,NaN,10000.0,2.000000,1375.0,30.401356,-97.752535
10857,78759,2017,9,419600.0,425000.0,222.164965,NaN,NaN,NaN,3.0,...,22,1,11,4,NaN,10000.0,2.335766,NaN,30.401356,-97.752535
10858,78759,2017,10,421500.0,444900.0,223.089176,NaN,NaN,NaN,3.0,...,22,1,11,4,NaN,10000.0,1.923077,NaN,30.401356,-97.752535
10859,78759,2017,11,422400.0,434950.0,222.827657,NaN,NaN,NaN,3.0,...,22,1,11,4,NaN,10000.0,2.299507,NaN,30.401356,-97.752535
10860,78759,2017,12,423500.0,425000.0,221.890393,NaN,NaN,NaN,3.0,...,22,1,11,4,NaN,10000.0,2.041233,NaN,30.401356,-97.752535
10861,78759,2018,1,424700.0,419900.0,218.079800,NaN,NaN,NaN,3.0,...,22,1,11,4,NaN,8000.0,2.067183,NaN,30.401356,-97.752535
10862,78759,2018,2,426300.0,420000.0,218.154149,NaN,NaN,NaN,3.0,...,22,1,11,4,NaN,10000.0,2.210955,NaN,30.401356,-97.752535
10863,78759,2018,3,429600.0,435000.0,224.252051,NaN,NaN,NaN,3.0,...,22,1,11,4,NaN,10250.0,2.865268,NaN,30.401356,-97.752535
10864,78759,2018,4,432600.0,432500.0,226.356334,NaN,NaN,NaN,3.0,...,22,1,11,4,NaN,10500.0,2.153025,NaN,30.401356,-97.752535

In [20]:
# bar_plot_1 = df_data[["Zip Code", "Year", "Month", "Home Value Index", "Median Income (dollars)"]]
bar_plot_1 = df_data[["Zip Code", "Year", "Month", "Home Value Index"]]
bar_plot_1

       Zip Code  Year  Month  Home Value Index
0         78701  1996      4          152500.0
1         78701  1996      5          153600.0
2         78701  1996      6          154600.0
3         78701  1996      7          155500.0
4         78701  1996      8          156300.0
5         78701  1996      9          157300.0
6         78701  1996     10          158300.0
7         78701  1996     11          159300.0
8         78701  1996     12          160400.0
9         78701  1997      1          161900.0
10        78701  1997      2          163500.0
11        78701  1997      3          164800.0
12        78701  1997      4          166300.0
13        78701  1997      5          167700.0
14        78701  1997      6          169000.0
15        78701  1997      7          170200.0
16        78701  1997      8          171500.0
17        78701  1997      9          172900.0
18        78701  1997     10          174500.0
19        78701  1997     11          176100.0
20        78701  1997     12          178000.0
21        78701  1998      1          180200.0
22        78701  1998      2          182700.0
23        78701  1998      3          185000.0
24        78701  1998      4          187500.0
25        78701  1998      5          189800.0
26        78701  1998      6          191800.0
27        78701  1998      7          193700.0
28        78701  1998      8          195500.0
29        78701  1998      9          197300.0
...         ...   ...    ...               ...
10835     78759  2015     11          381700.0
10836     78759  2015     12          383600.0
10837     78759  2016      1          385400.0
10838     78759  2016      2          387400.0
10839     78759  2016      3          390200.0
10840     78759  2016      4          393900.0
10841     78759  2016      5          398200.0
10842     78759  2016      6          402100.0
10843     78759  2016      7          405300.0
10844     78759  2016      8          408600.0
10845     78759  2016      9          411200.0
10846     78759  2016     10          413200.0
10847     78759  2016     11          414500.0
10848     78759  2016     12          414700.0
10849     78759  2017      1          415200.0
10850     78759  2017      2          416600.0
10851     78759  2017      3          417900.0
10852     78759  2017      4          418900.0
10853     78759  2017      5          419400.0
10854     78759  2017      6          419100.0
10855     78759  2017      7          418200.0
10856     78759  2017      8          418100.0
10857     78759  2017      9          419600.0
10858     78759  2017     10          421500.0
10859     78759  2017     11          422400.0
10860     78759  2017     12          423500.0
10861     78759  2018      1          424700.0
10862     78759  2018      2          426300.0
10863     78759  2018      3          429600.0
10864     78759  2018      4          432600.0

[10865 rows x 4 columns]

In [24]:
bar_plot_g = bar_plot_1.groupby(["Zip Code", "Year"])
bar_plot_g.mean()

               Month  Home Value Index
Zip Code Year
78701    1996    8.0     156422.222222
         1997    6.5     169700.000000
         1998    6.5     192250.000000
         1999    6.5     220891.666667
         2000    6.5     249466.666667
         2001    6.5     249825.000000
         2002    6.5     241050.000000
         2003    6.5     238466.666667
         2004    6.5     242366.666667
         2005    6.5     266058.333333
         2006    6.5     270983.333333
         2007    6.5     285691.666667
         2008    6.5     287425.000000
         2009    6.5     270208.333333
         2010    6.5     260200.000000
         2011    6.5     263208.333333
         2012    6.5     270133.333333
         2013    6.5     285300.000000
         2014    6.5     314166.666667
         2015    6.5     361616.666667
         2016    6.5     370500.000000
         2017    6.5     385658.333333
         2018    2.5     414575.000000
78702    1996    8.0      64055.555556
         1997    6.5      87983.333333
         1998    6.5     127016.666667
         1999    6.5     139941.666667
         2000    6.5     194808.333333
         2001    6.5     216125.000000
         2002    6.5     192783.333333
...              ...               ...
78758    2012    6.5     135441.666667
         2013    6.5     146491.666667
         2014    6.5     161850.000000
         2015    6.5     180133.333333
         2016    6.5     216641.666667
         2017    6.5     243800.000000
         2018    2.5     257900.000000
78759    1996    8.0     259677.777778
         1997    6.5     264333.333333
         1998    6.5     247108.333333
         1999    6.5     223466.666667
         2000    6.5     247041.666667
         2001    6.5     253075.000000
         2002    6.5     248658.333333
         2003    6.5     244625.000000
         2004    6.5     253725.000000
         2005    6.5     252583.333333
         2006    6.5     267741.666667
         2007    6.5     288341.666667
         2008    6.5     296183.333333
         2009    6.5     287800.000000
         2010    6.5     285533.333333
         2011    6.5     280575.000000
         2012    6.5     287833.333333
         2013    6.5     301066.666667
         2014    6.5     333141.666667
         2015    6.5     371325.000000
         2016    6.5     402058.333333
         2017    6.5     419200.000000
         2018    2.5     428300.000000

[943 rows x 2 columns]

In [45]:
#pass_read = df_students.loc[df_students["reading_score"]>=70,:]
test_1 = bar_plot_1.loc[bar_plot_1["Zip Code"]==78748, :]
test_1

      Zip Code  Year  Month  Home Value Index
7950     78748  1996      4          199400.0
7951     78748  1996      5          198700.0
7952     78748  1996      6          197900.0
7953     78748  1996      7          196600.0
7954     78748  1996      8          194900.0
7955     78748  1996      9          192700.0
7956     78748  1996     10          189900.0
7957     78748  1996     11          186700.0
7958     78748  1996     12          183400.0
7959     78748  1997      1          180100.0
7960     78748  1997      2          176700.0
7961     78748  1997      3          173000.0
7962     78748  1997      4          169300.0
7963     78748  1997      5          165500.0
7964     78748  1997      6          161700.0
7965     78748  1997      7          158200.0
7966     78748  1997      8          155100.0
7967     78748  1997      9          152700.0
7968     78748  1997     10          151000.0
7969     78748  1997     11          150200.0
7970     78748  1997     12          150500.0
7971     78748  1998      1          151700.0
7972     78748  1998      2          153300.0
7973     78748  1998      3          155400.0
7974     78748  1998      4          157700.0
7975     78748  1998      5          160000.0
7976     78748  1998      6          162100.0
7977     78748  1998      7          163800.0
7978     78748  1998      8          165100.0
7979     78748  1998      9          166100.0
...        ...   ...    ...               ...
8185     78748  2015     11          242900.0
8186     78748  2015     12          245100.0
8187     78748  2016      1          247200.0
8188     78748  2016      2          249000.0
8189     78748  2016      3          250800.0
8190     78748  2016      4          253000.0
8191     78748  2016      5          255000.0
8192     78748  2016      6          257000.0
8193     78748  2016      7          258900.0
8194     78748  2016      8          260200.0
8195     78748  2016      9          260400.0
8196     78748  2016     10          260700.0
8197     78748  2016     11          261100.0
8198     78748  2016     12          261300.0
8199     78748  2017      1          261900.0
8200     78748  2017      2          263400.0
8201     78748  2017      3          264800.0
8202     78748  2017      4          266000.0
8203     78748  2017      5          267000.0
8204     78748  2017      6          267900.0
8205     78748  2017      7          268300.0
8206     78748  2017      8          268900.0
8207     78748  2017      9          270300.0
8208     78748  2017     10          272600.0
8209     78748  2017     11          274800.0
8210     78748  2017     12          276300.0
8211     78748  2018      1          277400.0
8212     78748  2018      2          278500.0
8213     78748  2018      3          280200.0
8214     78748  2018      4          281400.0

[265 rows x 4 columns]

In [3]:
# figsize = (10, 8)
# fig = plt.figure(figsize=figsize)
# ax = fig.subplots(1, 1)

# labels = 'Frogs', 'Hogs', 'Dogs', 'Logs'
# height = [15, 30, 45, 10]

# title = "title"
# ylabel = "ylabel"

# bar(height, ticklabels=labels,
#     ylabel=ylabel,
#     ax=ax)